name: Deploy to Smithery

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Install Smithery CLI
        run: npm install -g @smithery/cli

      - name: Deploy to Smithery
        run: smithery deploy
        env:
          SMITHERY_TOKEN: ${{ secrets.SMITHERY_TOKEN }}
          SMITHERY_PROJECT: mcp-document-converter